### ISSUE TITLE
Archive otel-endusers channel

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#18]
Archive `otel-endusers` private slack channel. We are moving to `otel-sig-end-users` public channel.

**Comment by avillela** [comment]
Reached out to Ted to point us in the direction of the process for archiving channels.

**Comment by reese-lee** [comment]
Per Adriana, @danielgblanco will have to open a ticket with CNCF Service Desk to archive the private channel.

**Comment by danielgblanco** [comment]
Ticket created
