### ISSUE TITLE
Tracetest: OTel Q&A

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#20]
Tracetest has confirmed their participation for OTel Q&A on May 30th. We need to:

- [x] create a calendar invite & include both speakers below in the invite (@danielgblanco - [related issue](https://github.com/open-telemetry/community/issues/2109))
- [x] create a promo image for socials (@reese-lee)
- [x] promote on OTel socials (@avillela)

Participants from Tracetest:
* Oscar Reyes — [oscar@kubeshop.io](mailto:oscar@kubeshop.io)
* Daniel Dias — [daniel@kubeshop.io](mailto:daniel@kubeshop.io)

**Comment by reese-lee** [comment]
@avillela Does this work? 

![Image](https://github.com/open-telemetry/sig-end-user/assets/48657837/8ece32c2-3ed4-4297-8ed5-37d205dacc8a)

**Comment by avillela** [comment]
Looks great @reese-lee !

**Comment by avillela** [comment]
Created social promos for the coming weeks to promote the OTel Q&A session.

**Comment by avillela** [comment]
Also queued up announcements on various OTel Slack channels over the coming weeks: `otel-announcements`, `otel-sig-end-user`, `o11y-ambassadors`, `cncf-ambassadors`

**Comment by reese-lee** [comment]
@avillela I just got their headshots, I created another graphic we can use as well:



![Image](https://github.com/open-telemetry/sig-end-user/assets/48657837/66b7dbc6-fa61-4c7a-be7d-6f09461989aa)
