### ISSUE TITLE
Add standard demographic questions to surveys README

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#21]
I think it would be helpful to have a list of standard demographic questions that we collect about the folks who fill out our surveys. We should also add them to the survey [README](https://github.com/open-telemetry/sig-end-user/tree/main/end-user-surveys) so we have a place of reference when we create surveys.

Our surveys should include the following questions:

- [ ] How large is your organization (options: 0-50, 50-100, 100-1000, >1000)
- [ ] What industry do you work in? (options: Technology, Manufacturing, Aerospace, Retail, Finance, Healthcare, Automotive, Hospitality, Research, Travel & Leisure, Media, Advertisement, other)
- [ ] What type of team do you work on? (options: Dev, DevOps, Operations, SRE, Platform Engineering, Observability, Sysadmin, Sales Engineering, DevRel, other)
- [ ] Do you work for a vendor? (options: yes/no)

We should also include the following in the survey header:
* Purpose
* How long the survey will be open

**Comment by AnaMMedina21** [comment]
Add:
- Are you running this in Production? (option: yes/no)
- Where in your Observability journey is your organization? (options: 1) Beginner - Learning about observability / Have used monitoring tools, 2) Intermediate - We are setting up an observability practice, 3) Expert - We have a well-established observability practice)
