### ISSUE TITLE
Present OTel Collector survey findings to Maintainers

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#22]
As per suggestion from @tedsuo:

- [x] Create presentation summarizing main findings (max 5 slides)
- [ ] Schedule time to present results to maintainers
- [ ] Have a SIG member (the partner) co-present results @jpkrohling @IAMebonyhope 
- [ ] Upload slides & links to discussion panel recordings to [sig-end-user](https://github.com/open-telemetry/sig-end-user) repo
- [ ] Draft blog post and tag SIG in the PR for insight and data interpretation

**Comment by reese-lee** [comment]
[Blog post](https://opentelemetry.io/blog/2024/otel-collector-survey/) has been published.

**Comment by reese-lee** [comment]
@IAMebonyhope to aim for June 3 to present Collector survey findings to Maintainer meeting.

**Comment by jpkrohling** [comment]
Would it be possible to present it to the SIG Collector in addition to, or instead of, the Maintainer's meeting? 

https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.rbf22rxu3mij

**Comment by IAMebonyhope** [comment]
> Would it be possible to present it to the SIG Collector in addition to, or instead of, the Maintainer's meeting?
> 
> https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.rbf22rxu3mij

I am fine with either option...

@avillela @reese-lee what do you think about this??

**Comment by IAMebonyhope** [comment]
Also I have been really sick.. and just recovering.
So I wasnt able to prepare the slides for the maintainer meeting. 
Could we aim to present on June 10 instead??

**Comment by danielgblanco** [comment]
This was presented at the Maintainers meeting last week. @jpkrohling do you think this needs to be presented at the Collector meeting, or maybe the recording can be shared?

**Comment by jpkrohling** [comment]
I watched the recording, and while I don't think there's anything new there that wasn't on the blog post, I feel like we could have a moment with the Collector maintainers to reflect on the survey results. If the Collector SIG weekly call is the right place, I'm not sure. In any case, I shared a link to the recording to the collector leads and will come back to @IAMebonyhope if we need more clarification :-)

**Comment by avillela** [comment]
I'm in favour of over-communicating in this case, just to make sure that we reach all relevant parties in all ways possible. Just my two cents. 🙂

**Comment by danielgblanco** [comment]
For ease of access, the recording is here on the [Meeting Recordings](https://docs.google.com/spreadsheets/d/1SYKfjYhZdm2Wh2Cl6KVQalKg_m4NhTPZqq-8SzEVO6s/edit?gid=0#gid=0)

Maintainers + Community Weekly Meeting | 2024-06-10 9:00:28
-- | --

And it starts around the 20:00 mark.

**Comment by danielgblanco** [comment]
I think it'd be awesome for the results to be discussed in the Collector SIG meeting. If it's useful to have someone from the end-user SIG there for that let us know @jpkrohling .

**Comment by jpkrohling** [comment]
I definitely encourage one of you to join the Collector SIG calls, Wednesdays at 11am PT / 18:00 CEST. That said, I've heard that Collector SIG maintainers have seen the results a few times already, so, it might not be necessary unless you have something new to share.

**Comment by avillela** [comment]
Hmmmm...we definitely don't want to annoy them at that point, so perhaps we hold off at this point? One thing that would be helpful is to have action items tied to the survey results. @jpkrohling has that been addressed yet?

**Comment by jpkrohling** [comment]
I don't think there has been. This would certainly be a good discussion for the SIG.

**Comment by avillela** [comment]
Yes, we were just discussing on our meeting today, and we created #45 to capture this

**Comment by IAMebonyhope** [comment]
Slides used to present to the maintainers
https://1drv.ms/p/c/0a65d021ef4fe618/EWcXGmf_I7NJntlgIdb6oYIBHAp95k21Alu27zbJQlsH2w?e=QJcurD

**Comment by avillela** [comment]
Added PR for incorporating PDF into our repo.
