### ISSUE TITLE
Present OTel x Prom interoperability survey findings to Maintainers

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#24]
- [ ] Create presentation summarizing main findings (max 5 slides)
- [x] Schedule time to present results to maintainers
- [x] Have a SIG member (the partner) co-present results
- [ ] Upload slides & links to discussion panel recordings to [sig-end-user](https://github.com/open-telemetry/sig-end-user) repo
- [x] Draft blog post and tag SIG in the PR for insight and data interpretation

**Comment by reese-lee** [comment]
I spoke with @dashpole, he is planning to present the results on Aug 19. I think given that he has written a blog post about the survey results, we can probably mark the other items as done.

**Comment by dashpole** [comment]
Presented today.

**Comment by danielgblanco** [comment]
Thank you for all your work @dashpole! 🎉 Definitely some really interesting insights.
