### ISSUE TITLE
Embrace: OTel Q&A

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#25]
Embrace has confirmed their participation for OTel Q&A on June 27th. We need to:

- [x] create a calendar invite & include both speakers below in the invite (@danielgblanco - https://github.com/open-telemetry/community/issues/2120)
- [x] create a promo image for socials (@reese-lee)
- [x] promote on OTel socials (@avillela)
- [x] promote on Slack channels ( `#otel-announcements`, `#otel-sig-end-users`, `o11y-ambassadors`) (@avillela)
- [x] Prep Q&A doc
 
Participants from Embrace:
* Austin Emmons
* Eliab Sisay

**Comment by reese-lee** [comment]
OTel Q&A -- story of how they adopted OTel internally

**Comment by reese-lee** [comment]
![Image](https://github.com/open-telemetry/sig-end-user/assets/48657837/93d15bc1-3f04-4748-8b1b-d4eda80b4aeb)

**Comment by avillela** [comment]
Q&A doc [here](https://docs.google.com/document/d/1QgVkYdLQfY-yhyD9OFY-y3Si0kZZqhGuFqXnjoNZDMs/edit?usp=sharing)
