### ISSUE TITLE
Embrace: OTel in Practice

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#26]
Embrace has confirmed their participation for OTel in Practice on July 11th. We need to:

- [x] create a calendar invite & include both speakers below in the invite (@danielgblanco - https://github.com/open-telemetry/community/issues/2121)
- [x] create a promo image for socials (@reese-lee)
- [x] promote on OTel socials (@avillela)
- [x] promote on Slack channels ( `#otel-announcements`, `#otel-sig-end-users`, `o11y-ambassadors`) (@avillela)
 
Participants from Embrace:
* Hanson Ho
* Eliab Sisay

I'm waiting to hear back on details on the talk topic.

**Comment by reese-lee** [comment]
OTIP: Convo w/Client-Side Telemetry SIG -- vendor-neutral

**Comment by avillela** [comment]
![Image](https://github.com/open-telemetry/sig-end-user/assets/50256412/569a8d87-d3a6-407b-804c-0428e734eaf6)
