### ISSUE TITLE
Create survey template

### ISSUE THREAD

**Issue by reese-lee** [open-telemetry/sig-end-user#27]
Create a survey template for ease of use when creating surveys. 

Include questions from #21

**Comment by AnaMMedina21** [comment]
Here is the image I used for header in the Get Started Survey 
Color: `#415cc7`
![Image](https://github.com/open-telemetry/sig-end-user/assets/3894791/3dedd4a3-bdb8-4cbd-8f27-5ff42384869f)

**Comment by avillela** [comment]
Survey template can be found [here](https://docs.google.com/forms/d/e/1FAIpQLSdyUrH1EMEcNK3hVGCvms7VK-Cb5RJ1-ks4afWhDHOG2AhoOA/viewform?usp=sharing)
