### ISSUE TITLE
Live stream OTel Q&A and OTIPs

### ISSUE THREAD

**Issue by reese-lee** [open-telemetry/sig-end-user#28]
Context: Adriana has a private paid Streamyard account that she is happy to use for OTel EUSIG events. Goals:
* To gain more audience
* Raise awareness of EUSIG

Alternative: Use webinar-style Zoom.

- [x] Reach out to Austin re: Would it be okay to link a personal account to OTel socials?

**Comment by avillela** [comment]
Got super admin access from Austin so we can stream OTel sessions on LinkedIn
