### ISSUE TITLE
Brainstorm for New Survey: Docs Usability  

### ISSUE THREAD

**Issue by AnaMMedina21** [open-telemetry/sig-end-user#32]
After running the OpenTelemetry[ Getting Started Survey,](https://github.com/open-telemetry/sig-end-user/tree/main/end-user-surveys/getting-started) we learned folks wanted comprehensive documentation and we wanted to understand what kind of documentation that would be and also drill down on some more specific questions about the usability of our current docs. This issue is to kick-off a discussion about a possible next survey. 
Things to  include:
- Test out the new survey template with Demographic questions 
- Include Questions such as:
    * **Do you rely mostly on:**
        * OTel Docs
        * OTel README
        * Vendor Docs
    * **On a scale 1-5; How would you rate your experience using current documentation for $LANGUAGE?**
    * **On a scale 1-5; How easy to follow are installation instructions for OpenTelemetry?** 
    * **On a scale 1-5; How well do the current docs explain the different components of OTel?**
    * **Are there enough visuals (e.g., diagrams, screenshots) to explain OTel concepts?**
    * **How comprehensive are the troubleshooting sections?**
    * **Stack Rank possible tutorial categories**

**Comment by avillela** [comment]
Discussion thread on OTel Tutorials [here](https://github.com/open-telemetry/opentelemetry.io/discussions/4475#discussion-6662941).

Slack conversation ref [here](https://cloud-native.slack.com/archives/C02UN96HZH6/p1715615016338839)

**Comment by danielgblanco** [comment]
Thanks for creating this. I think a survey is 100% the right way forward. We need to make sure this reaches the right audience though, because some of the folks that care about docs may not be actively looking for OTel content (e.g. engineers that want to add some telemetry to their workloads already instrumented with OTel but who are not observability experts)

**Comment by AnaMMedina21** [comment]
From Ted: What docs are missing?

**Comment by AnaMMedina21** [comment]
From Alex B:  What's your favorite source of info about OTel?

**Comment by danielgblanco** [comment]
I think this survey should also aim to help us understand the profile of different types of end-users visiting our docs, and what their needs are. OTel is much more cross-cutting than other open-source projects that perhaps are targetted at a more specific audience (e.g. platform engineers).

Even within end-users (putting aside instro library authors) we have some end-users that are observability engineers and understand and care about collectors, configuring SDKs, etc. But, ultimately, many of the users of the API will have platform engineers that give them an already configured SDK out of the box. The only thing they want to know is "how do I get a Meter/Tracer/Logger and how do I measure some stuff?". I think identifying these end-user profiles via a survey would be super insightful.

**Comment by AnaMMedina21** [comment]
@svrnm Would you + Docs SIG be opening to running this survey for August?

**Comment by svrnm** [comment]
> @svrnm Would you + Docs SIG be opening to running this survey for August?

August is a down period for most people I know, including myself, so I would prefer something later.

Do we have the questions ready? To be honest I am currently out of capacity to help with that, will check with the rest of @open-telemetry/docs-approvers if someone can manage that.

**Comment by avillela** [comment]
We can run a new survey in September. We can certainly come up with some questions on our end, but some assitance/guidance from the rest of the @open-telemetry/docs-approvers would be very helpful!

**Comment by danielgblanco** [comment]
I've made https://docs.google.com/document/d/1le_kDcyMXR8LlCGSoPexe4SGSYP-EnY-JoB7fv1-k2g free to edit by anyone with the link. If anyone from @open-telemetry/docs-approvers wants to add some questions feel free.

If we get to it in time, this would be a great first use for https://github.com/open-telemetry/community/issues/2212

**Comment by avillela** [comment]
> https://docs.google.com/document/d/1le_kDcyMXR8LlCGSoPexe4SGSYP-EnY-JoB7fv1-k2g

Added a couple of comments.

**Comment by AnaMMedina21** [comment]
@svrnm Hey, did you talk to folks from SIG Docs to see if anyone wanted to take a lead on coming up with questions for this survey?

**Comment by svrnm** [comment]
> @svrnm Hey, did you talk to folks from SIG Docs to see if anyone wanted to take a lead on coming up with questions for this survey?

coming back from PTO: Not yet, but I send another reminder to @open-telemetry/docs-approvers :-)

**Comment by theletterf** [comment]
On it!

**Comment by reese-lee** [comment]
Hello @svrnm @theletterf ! Checking in on this with the following questions:

* How does the [survey draft](https://docs.google.com/document/d/1le_kDcyMXR8LlCGSoPexe4SGSYP-EnY-JoB7fv1-k2g) look to y'all currently? We want to make sure we capture data that's as useful to the Comms SIG as possible. 
* How does running it during the month leading up to KubeCon NA sound? Or do you have a different time frame in mind to align with some goals or something?

**Comment by svrnm** [comment]
@reese-lee overall it looks good to me, so I say, let's ship it. Running it leading up to KubeCon NA sounds good to me as well:-)

**Comment by reese-lee** [comment]
Sounds good! We'll go ahead and start putting things together (the survey, links, promos, etc.), and probably aim for a ship date within the next couple weeks.

**Comment by danielgblanco** [comment]
Closing this as survey is out and we have https://github.com/open-telemetry/sig-end-user/issues/69 to track it
