### ISSUE TITLE
OTel Q&A: Steven Swartz - Create Questions

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#57]
Create questions to ask Steven Swartz for upcoming OTel Q&A

Related: #54

**Comment by avillela** [comment]
[Q&A Doc](https://docs.google.com/document/d/14qCEW_keuxmjihnQYMpDmHk3IxAhG2Hx-oLoA2Y9QOU/edit?usp=sharing)

**Comment by danielgblanco** [comment]
Closing this as we've already done the Q&A
