### ISSUE TITLE
Draft SIG's new charter

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#6]
[Draft doc](https://docs.google.com/document/d/1Y-1kkSzeN_ugxbUNsZgOfbK7gPouHSEbWgjqwDcVjeM/edit) - awaiting reviews

**Comment by reese-lee** [comment]
https://docs.google.com/document/d/1Y-1kkSzeN_ugxbUNsZgOfbK7gPouHSEbWgjqwDcVjeM/edit

Draft is ready for review @avillela @danielgblanco

**Comment by avillela** [comment]
Looks good! I left a couple of comments!

**Comment by reese-lee** [comment]
Submitted a PR to add this to our repo! https://github.com/open-telemetry/sig-end-user/pull/60

**Comment by avillela** [comment]
Merged.
