### ISSUE TITLE
OTel Q&A with Dan Ravenstone - Create copy for social posts

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#62]
- [ ] create copy for promotion on OTel socials
- [ ] promote on Slack channels ( #otel-announcements, #otel-sig-end-users, o11y-ambassadors) - schedule posts to go out on October 8th, 15th, and 17th

Related: #61, #63, #64, #65, #66

**Comment by LisaHJung** [comment]
Hey @avillela , I got the following approved by the Q and A guest, Dan Ravenstone.

This copy has been posted to:
#otel-sig-end-user
#otel-announcements
#o11y-ambassadors
------
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjliNDRzMXBxcHdvNnQ5YWI2eTdmOG82NW04bWIxdWJjbHI4c3o5cyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/DPznISmq0hLRQqG71g/giphy.gif)

It’s time for another OTel Q and A session! 

In this much-anticipated event, we will feature Dan Ravenstone, a staff engineer at Top Hat. 

During his 25 years as an observability engineer, he had a front-row seat in observing the evolution of observability and the cultural hurdles that have persisted throughout the years. 

Join us to hear about Dan’s experiences and challenges around OTel adoption.

WHEN: Thursday, October 17th, 1 PM - 2 PM EDT (GMT-4)
WHERE: https://zoom.us/j/94248708389?pwd=U4d4ezafHaq01KfOb3dB9jRPlUTeer.1

See you there! 
-----

**Comment by LisaHJung** [comment]
@avillela , I just updated all the event links for the Slack posts that went out today.
These posts have been scheduled to go out on October 8th, 15th, and 17th at 11 AM EST on all three channels mentioned above.

**Comment by avillela** [comment]
**Social copy for Twitter/Bluesky:**
It's time for [#OTel](https://twitter.com/#!/search?q=%23OTel) Q&A, featuring Dan Ravenstone. During his 25 years as an o11yneer, he's had a front-row seat in observing the evolution of o11y and the cultural hurdles that have persisted throughout the years.

WHEN: Oct 17th @ 13:00ET/10:00PT
JOIN: https://community.cncf.io/j/86u3h5bahrjz4/

**Social copy for Mastodon/LinkedIn:**
It's time for [#OTel](https://www.linkedin.com/feed/hashtag/?keywords=OTel) Q&A, featuring Dan Ravenstone, staff engineer at Top Hat. During his 25 years as an observability engineer, he has had a front-row seat in observing the evolution of observability and the cultural hurdles that have persisted throughout the years.

Join us to hear about Dan’s experiences and challenges around OTel adoption.

WHEN: Oct 17th @ 13:00ET/10:00PT
JOIN: https://community.cncf.io/j/86u3h5bahrjz4/

** Be sure to attach social card!!
