### ISSUE TITLE
OTel Q&A with Dan Ravenstone - Create Q&A doc

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#63]
- [ ] Prep Q&A doc

Related: #61, #62, #64, #65, #66

**Comment by reese-lee** [comment]
Here is the Q&A template doc! (I already had it added to the issue template that Dan created.) 

https://docs.google.com/document/d/1vi6NpSj3MvKTuNwFpE8toywHP0sWiH4bsE3AOWvgSwo/edit?tab=t.0

**Comment by avillela** [comment]
Q&A doc for Dan [here](https://docs.google.com/document/d/124ODeIylxTMGV7TSXeM4hQcddCv3wPnmKJc26xvRTEM/edit?usp=sharing)
