### ISSUE TITLE
Cancel End User Discussion groups

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#7]
* Remove from Meetup.com
* Talk to APAC hosts (Reese posted in the private hosts channel)
* Create message in Slack channel 
* [Dan] Cancel calendar events

**Comment by danielgblanco** [comment]
I've cancelled EMEA and AMER events, but APAC is still ongoing. From discussions on Slack, it looks like it'd make sense to cancel those too and focus on feedback sessions or user panels.

**Comment by ankit01-oss** [comment]
Remove APAC sessions from [OpenTelemetry discussion group page](https://opentelemetry.io/community/end-user/discussion-group/).

**Comment by danielgblanco** [comment]
Thanks @ankit01-oss, bringing some context into this issue from Slack conversations:

> Mainly because it has turned into a support query forum, and not leading to much feedback for otel contributors 

This is aligns with the main reasons behind the cancellation of EMEA and AMER and the overall context provided in https://github.com/open-telemetry/community/issues/2052.

As with that issue, I'd urge maintainers or end-users to raise issues in https://github.com/open-telemetry/sig-end-user to organise specific, focused Q&A/feedback panels with end-users and maintainers. We should be able to accommodate APAC times too!

**Comment by musingvirtual** [comment]
I've already done all of these tasks (this issue was created well after the initial discussion).

Assuming Dan has canceled the calendar event we can close this one.

**Comment by danielgblanco** [comment]
I'd wait to close it until https://github.com/open-telemetry/opentelemetry.io/pull/4450 is merged

**Comment by danielgblanco** [comment]
I've just cancelled the APAC event in the OTel Public Calendar. @musingvirtual do we still have the APAC event in meetup.com?

@ankit01-oss do you think we need to communicate this in Slack? We have done so already for the other groups (see this [message](https://cloud-native.slack.com/archives/C01RT3MSWGZ/p1713176434312119))

**Comment by danielgblanco** [comment]
All merged, events cancelled and website updated.
