### ISSUE TITLE
KubeCon NA 2024 OTel Observatory schedule planning

### ISSUE THREAD

**Issue by reese-lee** [open-telemetry/sig-end-user#72]
Per our SIG meeting, this issue is to track tasks for planning the schedule for the OTel Observatory. See [this doc](https://docs.google.com/document/d/1glRLssapJVLOOJL1u36g_ihI5-CWQclHvZXWPNCRvtc/edit?tab=t.0) for additional info. 

- [x] Find out who (maintainers) will be in attendance @AnaMMedina21 
- [x] How to post the schedule at the booth? – reach out to Austin re: can we use the screen at the booth? 
- [x] Collect a list of OTel sessions with times @reese-lee 
- [x] Finalize list of SIGs in attendance @AnaMMedina21 
- [x] Confirm maintainers for Office Hour sessions @reese-lee 
- [x] Confirm maintainers for other activities as needed @reese-lee 
- [x] Create schedule for Humans of OTel interviews @avillela 
- [x] Confirm maintainers/contributors for Humans of OTel 
- [x] Promote!

Please feel free to self-assign any of these tasks to yourself, and add any tasks that are not included here.

**Comment by AnaMMedina21** [comment]
Happy to take on `Find out who (maintainers) will be in attendance` & 
`Finalize list of SIGs in attendance` again this iteration

**Comment by IAMebonyhope** [comment]
@reese-lee I could help with updating the kubecon blogpost with the schedule for office hour sessions and other end-user activities if needed. (once we finalize them).

**Comment by danielgblanco** [comment]
I've marked the tasks that were done here as such. Thanks for taking care of this!
