### ISSUE TITLE
Community Tools for Slack contribution

### ISSUE THREAD

**Issue by LisaHJung** [open-telemetry/sig-end-user#74]
**Challenge**
At present, our organization does not have a way to visualize Slack contributions and celebrate community members who are making contributions. 

**Community tools**

[Common Room](https://www.commonroom.io/)
_Pros_
- A view of what’s happening on various platforms such as Slack, StackOverflow, Reddit, etc 

_Cons_
- Expensive
<img width="619" alt="image" src="https://github.com/user-attachments/assets/b5dcf6fc-5b58-4946-aa8a-c594659e75e1">

[Orbit](https://orbit.love/)
_Pros_
- A view of what’s happening on various platforms such as Slack, StackOverflow, Reddit, etc 
- Cost
  - Free tier with unlimited community members
  - Possibility of getting more capacity as a non-commercial open source project 
<img width="513" alt="image" src="https://github.com/user-attachments/assets/c66ce144-340d-4fef-bff7-64d3ea4df91d">

_Cons_	
- Recently acquired by Postman
- Messaging from the Orbit Team
  - The current Orbit product will be shutting down, and Orbit users have 90 days to wind down their use of Orbit and export their data 
  - On May 31 we will stop ingesting new data, but you will still have access to explore and export your data until July 11
  - Existing customers will get support during the 90-day period, and customers who prepaid annually will receive prorated refunds
  - The Orbit team will be working on the Postman API Network, building new tools to help API publishers grow their developer communities 

[Waves](https://meetwaves.com/slack_community_analytics_tool)
_Pros_
- Slack analytics tool that monitors # of Slack threads, and track top messages, and trending posts.

_Cons_
- Sole focus on Slack - cannot extend to other platforms our community members may be contributing to. 
- Less expensive than Common Room but still incurs monthly costs
<img width="571" alt="image" src="https://github.com/user-attachments/assets/47794072-5d40-42d0-aaa5-518e48d2fcca">

**Alternative option**
Building a custom tool
_Pros_
- Slack webhooks

_Cons_
- Involves writing custom Code
- Bandwidth
- Who will manage this?

**Comment by danielgblanco** [comment]
Considering we're moving forward with Community Awards, and the GC has agreed not to encourage the metrification of Slack contributions, does it make sense to keep this open?

I really appreciate your effort here @LisaHJung, this has definitely brought some more info to the table, as there doesn't seem to be an easy solution out there to do this sort of thing.

**Comment by LisaHJung** [comment]
Hi @danielgblanco ! 

I really love your idea about the Community Awards and that we are taking steps to make that happen.

Given that we already have something in place to celebrate our community's contributions which was the intention behind considering tools to track Slack contributions, I say we close this issue for the time being and revisit it if necessary.

Thank you so much for your leadership in this area and for taking a great step to start recognizing our community members. This is such an important initiative and I am glad we are playing a part in it!

**Comment by danielgblanco** [comment]
Thanks @LisaHJung, I'm closing this issue accordingly.
