### ISSUE TITLE
Access to CNCF Cloud Native Community Groups platform

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#8]
Access to CNCF [Cloud Native Community Groups](https://community.cncf.io/) platform
* Dan to raise Service Desk ticket
* Rynn to create issue in community repo

**Comment by danielgblanco** [comment]
@musingvirtual were you thinking of a community group in general for OTel end-users?

**Comment by reese-lee** [comment]
@danielgblanco to create ticket with Service Desk to:

- [ ] Create an OpenTelemetry community group named "OpenTelemetry".
- [ ] Confirm whether we can modify the page ourselves. [Keptn's CG page](https://community.cncf.io/keptn-community/) as reference. 
- [ ] Share feedback about the Twitter/X API (makes it look very outdated).

**Comment by danielgblanco** [comment]
On the above, I will initially add participants in this issue to the list of requested organisers of the group

**Comment by danielgblanco** [comment]
Ticket created, I've not asked to include the organisers yet, but rather how organisers would be added (if via service desk or one organiser can add others)

**Comment by danielgblanco** [comment]
Related to Twitter/X API and posts not up-to-date, I think we were too fast to RCA that :D Looking at https://x.com/CloudNativeFdn it seems that account (where community groups get their feed from) has not been active.

**Comment by danielgblanco** [comment]
From support, regarding how to add people are organizers.

> Each person that needs to be an organizer would need to create a profile on [community.cncf.io](http://community.cncf.io/) and then you can share the list in this ticket and I will add them

Am I right in thinking organizers would be the following?

- @avillela 
- @reese-lee 
- @musingvirtual 
- @danielgblanco

**Comment by danielgblanco** [comment]
If you could create your profiles (see mine https://community.cncf.io/u/m5rbbe) I could then share them with the team to add us as organizers. This can later be modified, of course.

**Comment by musingvirtual** [comment]
Done: [https://community.cncf.io/u/m9783a/#/about](https://community.cncf.io/u/m9783a/)

**Comment by reese-lee** [comment]
✅ https://community.cncf.io/u/mcxrj5/#/about

**Comment by danielgblanco** [comment]
Thanks. @AnaMMedina21 and @IAMebonyhope when you have a chance, could you do the same? That way we can get all future `end-user-sig-approvers` (after team is created) as organizers in the community group

**Comment by IAMebonyhope** [comment]
Here is mine: https://community.cncf.io/u/mbdek9/#/about

**Comment by avillela** [comment]
Here's mine: https://community.cncf.io/u/mg62up/#/about

**Comment by AnaMMedina21** [comment]
Here is mine: https://community.cncf.io/u/myukru/

**Comment by danielgblanco** [comment]
I've just asked for an update (still waiting on support)

**Comment by musingvirtual** [comment]
I just got a "welcome new chapter organizer" (containing additional steps, so others might want to look for the email as well) so I am assuming they have done the thing!

**Comment by danielgblanco** [comment]
I guess that just needed a reminder :) Page in https://community.cncf.io/opentelemetry so we'll consider this done!
